version: "2"
services:

  mongos1:
    container_name: mongos1
    image: mongo:3.0.14
    environment:
      TERM: xterm
    # ports:
    #   - 5001:27017
    volumes:
      - /home/abhishekvtangod/Documents/fy_project/data/mongors1n1:/data/db

  mongos2:
    container_name: mongos2
    image: mongo:3.0.14
    environment:
      TERM: xterm
    # ports:
    #   - 5002:27017
    volumes:
      - /home/abhishekvtangod/Documents/fy_project/data/mongors1n2:/data/db

  mongos3:
    container_name: mongos3
    image: mongo:3.0.14
    environment:
      TERM: xterm
    # ports:
    #   - 5003:27017
    volumes:
      - /home/abhishekvtangod/Documents/fy_project/data/mongors1n3:/data/db

  mongos4:
    container_name: mongos4
    image: mongo:3.0.14
    environment:
      TERM: xterm
    # ports:
    #   - 5004:27017
    volumes:
      - /home/abhishekvtangod/Documents/fy_project/data/mongors2n1:/data/db

  mongos5:
    container_name: mongos5
    image: mongo:3.0.14
    environment:
      TERM: xterm
    # ports:
    #   - 5005:27017
    volumes:
      - /home/abhishekvtangod/Documents/fy_project/data/mongors2n2:/data/db

  mongos6:
    container_name: mongos6
    image: mongo:3.0.14
    environment:
      TERM: xterm
    # ports:
    #   - 5006:27017
    volumes:
      - /home/abhishekvtangod/Documents/fy_project/data/mongors2n3:/data/db

  mongoexpress1:
      container_name: mongoexpress1
      image: mongo-express
      ports:
          - "8001:8081"
      links:
          - mongos1
      environment: 
          - ME_CONFIG_MONGODB_URL=mongodb://mongos1:27017
  mongoexpress2:
      container_name: mongoexpress2
      image: mongo-express
      ports:
          - "8002:8081"
      links:
          - mongos2
      environment: 
          - ME_CONFIG_MONGODB_URL=mongodb://mongos2:27017
  mongoexpress3:
      container_name: mongoexpress3
      image: mongo-express
      ports:
          - "8003:8081"
      links:
          - mongos3
      environment: 
          - ME_CONFIG_MONGODB_URL=mongodb://mongos3:27017
  mongoexpress4:
      container_name: mongoexpress4
      image: mongo-express
      ports:
          - "8004:8081"
      links:
          - mongos4
      environment: 
          - ME_CONFIG_MONGODB_URL=mongodb://mongos4:27017
  mongoexpress5:
      container_name: mongoexpress5
      image: mongo-express
      ports:
          - "8005:8081"
      links:
          - mongos5
      environment: 
          - ME_CONFIG_MONGODB_URL=mongodb://mongos5:27017
  mongoexpress6:
      container_name: mongoexpress6
      image: mongo-express
      ports:
          - "8006:8081"
      links:
          - mongos6
      environment: 
          - ME_CONFIG_MONGODB_URL=mongodb://mongos6:27017
