version: "2.4"
services:

  mongos1:
    container_name: mongos1
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume1:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos2:
    container_name: mongos2
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume2:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos3:
    container_name: mongos3
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume3:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos4:
    container_name: mongos4
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume4:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos5:
    container_name: mongos5
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume5:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos6:
    container_name: mongos6
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume6:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos7:
    container_name: mongos7
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume7:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos8:
    container_name: mongos8
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume8:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos9:
    container_name: mongos9
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume9:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1

  mongos10:
    container_name: mongos10
    image: mongo:latest
    restart: unless-stopped
    environment:
      TERM: xterm
    volumes:
      - mongovolume10:/data/db
    mem_limit: 2000m
    mem_reservation: 2000m
    cpus: 0.1


  mongoexpress1:
    container_name: mongoexpress1
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos1
    ports:
        - "8001:8081"
    links:
        - mongos1
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos1:27017
  mongoexpress2:
    container_name: mongoexpress2
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos2
    ports:
        - "8002:8081"
    links:
        - mongos2
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos2:27017
  mongoexpress3:
    container_name: mongoexpress3
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos3
    ports:
        - "8003:8081"
    links:
        - mongos3
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos3:27017
  mongoexpress4:
    container_name: mongoexpress4
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos4
    ports:
        - "8004:8081"
    links:
        - mongos4
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos4:27017
  mongoexpress5:
    container_name: mongoexpress5
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos5
    ports:
        - "8005:8081"
    links:
        - mongos5
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos5:27017

  mongoexpress6:
    container_name: mongoexpress6
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos6
    ports:
        - "8006:8081"
    links:
        - mongos6
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos6:27017
  

  mongoexpress7:
    container_name: mongoexpress7
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos7
    ports:
        - "8007:8081"
    links:
        - mongos7
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos7:27017
  

  mongoexpress8:
    container_name: mongoexpress8
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos8
    ports:
        - "8008:8081"
    links:
        - mongos8
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos8:27017
  

  mongoexpress9:
    container_name: mongoexpress9
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos9
    ports:
        - "8009:8081"
    links:
        - mongos9
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos9:27017
  

  mongoexpress10:
    container_name: mongoexpress10
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongos10
    ports:
        - "80010:8081"
    links:
        - mongos10
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongos10:27017
  

  main_node:
    image: abhishekvtangod/main_node
    container_name: main_node
    build:
      context: ./app/main
    depends_on:
      - mongos1
      - mongos2
      - mongos3
      - mongos4
      - mongos5
      - mongos6
      - mongos7
      - mongos8
      - mongos9
      - mongos10
    ports:
      - "5001:8080"
    volumes:
      - ./app/main:/app
  single_node:
    image: abhishekvtangod/single_node
    container_name: single_node
    build:
      context: ./app/single-node
    depends_on:
      - mongos1
      - mongos2
      - mongos3
      - mongos4
      - mongos5
      - mongos6
      - mongos7
      - mongos8
      - mongos9
      - mongos10
    ports:
      - "5002:8080"
    volumes:
      - ./app/single-node:/app
    
volumes:
  mongovolume1: 
  mongovolume2: 
  mongovolume3: 
  mongovolume4: 
  mongovolume5: 
  mongovolume6: 
  mongovolume7: 
  mongovolume8: 
  mongovolume9: 
  mongovolume10: 

# networks:
#   default:
#     driver: overlay